
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class StaffLogin extends javax.swing.JFrame {

    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
        lblPassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmp = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginPage");
        setMinimumSize(new java.awt.Dimension(400, 350));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel1.setText("STAFF LOGIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 40, 120, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 140, 90, 30);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(150, 140, 179, 30);

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(250, 220, 100, 30);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(150, 260, 90, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel3.setText("© NNNS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 260, 90, 20);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel5.setText("EmpID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 90, 90, 30);

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("Tunga", 0, 14)); // NOI18N
        lblPassword.setText("Incorrect Credentials Please Try Again");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(70, 190, 260, 19);
        getContentPane().add(txtEmp);
        txtEmp.setBounds(150, 90, 180, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 260, 100, 30);

        btnBack1.setBackground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Forget Password");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack1);
        btnBack1.setBounds(20, 220, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Documents\\nh\\Restaurant-Order-System-master\\Grey1.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String password = txtPassword.getText();
        String empId = txtEmp.getText();
        //if statement to validate user input for admin password
        if(empId.equals("rohan") && password.equals("password") ){
            //if entered string mathces the password, it will display the admin home screen, and make it visible
            Homepage f = new Homepage("Rohan");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("arjun") && password.equals("password"))){
             Homepage f = new Homepage("Arjun");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("akshay") && password.equals("password"))){
             Homepage f = new Homepage("Akshay");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("aditya") && password.equals("password"))){
             Homepage f = new Homepage("Aditya");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("ankit") && password.equals("password"))){
             Homepage f = new Homepage("Ankit");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("sarthak") && password.equals("password"))){
             Homepage f = new Homepage("Sarthak");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("chetana") && password.equals("password"))){
             Homepage f = new Homepage("Chetana");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("rajesh") && password.equals("password"))){
             Homepage f = new Homepage("Rajesh");
            this.setVisible(false);
            f.setVisible(true);
        }
        else if((empId.equals("suchetha") && password.equals("password"))){
             Homepage f = new Homepage("Suchetha");
            this.setVisible(false);
            f.setVisible(true);
        }
        else{
            //empties the password field and informs user they are wrong
            txtPassword.setText(null);
            lblPassword.setVisible(true);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        homeIndex h = new homeIndex();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        if("".equals(txtEmp.getText())){
            JOptionPane.showMessageDialog(null, "Please enter Employee ID");
        }
        else{
            JOptionPane.showMessageDialog(null, "A Message is being send to your registerd mobile Number");
         try {          
                        
 //Construct data
String apiKey = "apikey=" + "yFzgpjufR4Y-nZ9okDBx9hQLWr1b6Usi4vwMsibbML";
String message = "&message=" + "Your Password is 'password'";
String sender = "&sender=" + "TXTLCL";
String numbers = "&numbers=" + "918384845571";

// Send data
HttpURLConnection conn = (HttpURLConnection) new URL("https://api.textlocal.in/send/?").openConnection();
String data = apiKey + numbers + message + sender;
conn.setDoOutput(true);
conn.setRequestMethod("POST");
conn.setRequestProperty("Content-Length", Integer.toString(data.length()));
conn.getOutputStream().write(data.getBytes("UTF-8"));
                    try (BufferedReader rd = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {
                        final StringBuffer stringBuffer = new StringBuffer();
                        String line;
                        while ((line = rd.readLine()) != null) {
                            stringBuffer.append(line);
                        }
                    }


} catch (Exception e) {
System.out.println("Error SMS "+e);

}
        }
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmp;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
